<?php
// [ai-generated-code]

namespace Database\Factories;

use App\Models\Node;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Node>
 */
class NodeFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Node::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $types = ['Technology', 'Person', 'Theory', 'Concept', 'Method', 'Tool'];
        $sources = ['YouTube Video', 'Blog Article', 'Book', 'Academic Paper', 'Podcast', 'Course'];
        $colors = ['#4285F4', '#EA4335', '#FBBC05', '#34A853', '#8E44AD', '#3498DB', '#E74C3C'];
        
        // Mock embedding vector (in reality, this would be generated by an embedding model)
        $embedding = [];
        for ($i = 0; $i < 5; $i++) {
            $embedding[] = $this->faker->randomFloat(6, -1, 1);
        }
        
        return [
            'label' => $this->faker->unique()->words(3, true),
            'description' => $this->faker->paragraph(),
            'type' => $this->faker->randomElement($types),
            'source' => $this->faker->randomElement($sources),
            'embedding' => $embedding,
            'color' => $this->faker->randomElement($colors),
        ];
    }
} 